[package]
name = "giter-watcher"
authors = ["Fanick"]
version = "0.0.1"

[dependencies]
notify = { version = "6.1.1", features = ["serde"] }
dashmap = {version = "6.1.0", features = ["rayon"]}
rayon = "1.10.0"
log = "0.4.22"
parking_lot = "0.12.3"